# compose.build.yml
services:
  backend:
    # Definiert, wie das Image gebaut wird
    build:
      context: ./backend
      args:
        - GIT_COMMIT_SHA=${GIT_COMMIT_SHA:-unknown}
        - SENTRY_DSN=${SENTRY_DSN:-}
    image: mrunknownde/utools-backend:latest

  frontend:
    # Definiert, wie das Image gebaut wird
    build:
      context: ./frontend
    image: mrunknownde/utools-frontend:latest